### ISSUE TITLE
1.18.2

### ISSUE THREAD

**Issue by itsdinkd** [CleverNucleus/DataAttributes#11]
Hello, i am the creator of Another Quality Modpack 2. I've been using Data Attributes since our 1.17 release. I was wondering if there will be a 1.18.2 port?

**Comment by CleverNucleus** [comment]
Hi there,
It is now being worked on. I was on hiatus from modding over April. There are some (surprising) technical challenges porting from 1.18.1 to 1.18.2, as Mojang made changes under the hood that are particularly relevant to Data Attributes.

In terms of a timeline/release date, I do not know for certain when I will finish updating - I expect to have a release early/mid May, but that is subject to change.
Hope that helps,
Thanks.

**Comment by itsdinkd** [comment]
Sounds good, thank you! I can patiently wait for it, no problem. :)
