### ISSUE TITLE
How to make second entity attribute.

### ISSUE THREAD

**Issue by quackgoestheduck** [CleverNucleus/DataAttributes#4]
When I try to add an attribute to one entity it works but when I try to add a second entity with an edited attribute it doesn't work. The wiki does not state how to add multiple entity attributes.
[help.txt](https://github.com/CleverNucleus/DataAttributes/files/7965233/help.txt)

Help would be much appreciated.

**Comment by CleverNucleus** [comment]
Hi there,
No worries, your problem is just a bit of malformed json - here is what you need:
```
{
    "values": {
        "adventurez:amethyst_golem": {
            "minecraft:generic.max_health": 240.0
        },
        "adventurez:stone_golem": {
            "minecraft:generic.max_health": 2400.0
        }
    }
}
```
The wiki assumes a prerequisite level in json, but you're right it could be clearer on some things, I'll make some amendments.
Hope that helps, thanks.
