### ISSUE TITLE
"this.StackingBehavior" returning null?

### ISSUE THREAD

**Issue by HockeyZman2000** [CleverNucleus/DataAttributes#6]
Not quite sure what is going on here. Maybe you could take a look for me? Mentions DataAttributes.

Crash Report:
[crash-2022-02-03_22.07.00-server.txt](https://github.com/CleverNucleus/PlayerEx/files/7999992/crash-2022-02-03_22.07.00-server.txt)

Log: 
[latest.log](https://github.com/CleverNucleus/PlayerEx/files/7999995/latest.log)

**Comment by CleverNucleus** [comment]
Hi there,
I've looked through your (extensive) mod list and found nothing that would cause this issue. The only way this specific crash can happen is if there is a malformed json in `data/.../attributes/overrides/`. I see that you were not using any datapacks when the crash occurred, therefore I can only say that either one of your jsons in PlayerEx or another mod jar has been a) corrupted or b) modified. I've verified that the releases provided on Curseforge do not have any malformed json - I can only advise that you redownload PlayerEx and DataAttributes from Curseforge, and check that non of your other mod files have modified attribute jsons.

I won't close the issue immediately in case you have other information, but I can confirm that there is no issue with the mod itself, just potentially malformed jsons from an unknown source.
Thanks.
