### ISSUE TITLE
Exception Ticking World (Quilt 1.19.2)

### ISSUE THREAD

**Issue by ViaBeans** [CleverNucleus/DataAttributes#94]
Receiving thios log error multiple times, usually linked with server stressing operations like chunk loading, but also using the UI for player attributes like the rpg mod I was using that lead to this recent crash.

[crash-2023-07-01_14.51.20-server.txt](https://github.com/CleverNucleus/data-attributes/files/11926448/crash-2023-07-01_14.51.20-server.txt)

Here's the log.

**Comment by CleverNucleus** [comment]
Duplicate of #93
