### ISSUE TITLE
server side crash because of mansion

### ISSUE THREAD

**Issue by DadoIrie** [CleverNucleus/DataAttributes#96]
as only Data Attributes is mentioned I'll report it meanwhile, but it might be most likely a conflict here - which I'm still trying to figure out, but with the amount of mods this might be taking a while (but if having suspicion it would be real helpful)

after removing one structures mod the locating did not crash anymore (which happened 3 times with that structures mod removed)
after removing that structure mod locating when fine, just when teleporting to that coordinates of the minecraft:mansion server crashes

crashlog: https://mclo.gs/OW5NYw0

after removing PlayerEx, RelicEx, WizardEx & Data Attributes no such crashed occurred after teleporting to the mansion
will investigate further and see which of those Ex's are causing the crash and if it's one of them I will move this issue to the appropriate Github

**Comment by DadoIrie** [comment]
found the conflict: [Illager Expansion [Rematch]](https://modrinth.com/mod/illager-expansion-rematch)

log file: https://mclo.gs/HaF7Ndo

UPDATE: has no hurry since this mod has other issues besides that one and therefore not using it anymore - the crash also might be not even data attributes fault at all

**Comment by CleverNucleus** [comment]
Hi there,
I am aware of the issue - it is to do with the unconventional way Illager Expansion uses to register attributes. I have made a [PR](https://github.com/ZekeSmith/Illager-Expansion-Rematch/pull/11) on their github with an easy-to-implement fix and therefore consider this matter closed.

Regardless, I appreciate you taking the time to troubleshoot the issue.
Thanks.

**Comment by DadoIrie** [comment]
thanks a lot for that PR
